### ISSUE TITLE
Support zip packaging

### ISSUE THREAD

**Issue by rbellamy** [dancingrobot84/sbt-idea-plugin#8]
Currently the `ideaPluginFile` points to the JAR created during the `package` task. This works for plugins that have zero dependencies, however most Scala-based plugins will still fail to load in IntelliJ installed as pure JAR files because they will be missing the Scala runtime libraries.

You can see my experience trying to install a plugin in this manner at https://github.com/olafurpg/scalafmt/pull/655#issuecomment-269378877.

After further reading it seems to me the missing step is the ability to wrap the packaged JAR into a zip that includes the necessary dependencies (a la the [`sbt-native-packager`](https://github.com/sbt/sbt-native-packager) `packageBin` task) using the format described in [Plugin Content](http://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_content.html).

Having the option to publish both a JAR and a ZIP plugin package is ideal.

**Comment by nkly** [comment]
Hi! Thanks for pointing out the issue. Unfortunately, just wrapping jar into zip is not the correct way to solve it because plugins differ: some may include plugin for [External Builder](http://www.jetbrains.org/intellij/sdk/docs/reference_guide/frameworks_and_external_apis/external_builder_api.html) or other jars that aren't direct dependencies, but still need to be included. An example of such convoluted plugin is IntelliJ Scala -- take a look at [these lines](https://github.com/JetBrains/intellij-scala/blob/idea163.x/build.sbt#L223). On the other hand, if your plugin is simple, you can use `sbt-assembly` to make a fat jar with all the dependencies you need in a couple lines of code. Therefore, I think it's better to stand out of the way of plugin maker and let him decide himself how the plugin should be packaged.
